### ISSUE TITLE
Logic bug in extend()

### ISSUE THREAD

**Issue by Joeysantoro** [delegatexyz/delegate-market#1]
https://github.com/delegatecash/liquid-delegate/blob/921603d8231be2b765a923d760ff7b027d0c6165/src/LiquidDelegate.sol#L155

I think this should be 
```
if (!(ownerOf(liquidDelegateId) == msg.sender && newExpiration > rights.expiration)) {
```
The || condition as written would allow anyone to extend any LD.

Also maybe I'm misunderstanding the use case here but shouldn't the first clause check against the depositor not the owner? Otherwise the owner can also indefinitely extend the delegation once the depositor has transferred ownership.

**Comment by 0xfoobar** [comment]
Fixed, thanks!
