### ISSUE TITLE
"Invalid input" no matter name of name on the wallet you try to delegate, initial state fails and "Submit Delegation"-button disabled

### ISSUE THREAD

**Issue by ralle121212** [delegatexyz/delegate-market#4]
I ran into an error in Opera browser when trying to delegate my wallet, connecting was of no problem but whatever name I put in the input-box gets rejected as "Invalid input" and thus the "Submit Delegation" button gets disabled. Look at the dev tools also, were initial state fails. You use deprecated "eval"? 

![DelegateCashInitialStateError](https://user-images.githubusercontent.com/84081830/237032853-b73533a2-a94b-4e23-9e12-3a3a59f5d610.png)

**Comment by ryespresso** [comment]
Hey @ralle121212 - unfortunately I was not able to replicate. Downloaded the latest version of Opera and it seems to be working fine on my end. Going to close this for now.  I'm sorry I couldn't be more help.

* I would double check you don't have any conflicting plugins and that your version is up to date
* Low priority, but I will eventually spin up a windows machine and test it on Opera to double check.

--
Re: You use deprecated "eval" -  We use sveltejs and I'm unaware of their usage of eval() when compiling. This notice does not show up on my machine. It may possibly be one of your plugins or it may be Windows specific.

**Comment by ralle121212** [comment]
Might be you're right, could be the plugins maybe.. However I wanted to get you noticed on this however, if it were serious and might then have ended with some serious complications for the project, which had been unfortunate in that case.  So its only good you couldn't replicate it!
